// All major cities and municipalities of Colombia
export const COLOMBIAN_CITIES: string[] = [
  "Bogota",
  "Medellin",
  "Cali",
  "Barranquilla",
  "Cartagena",
  "Bucaramanga",
  "Cucuta",
  "Pereira",
  "Santa Marta",
  "Ibague",
  "Manizales",
  "Villavicencio",
  "Pasto",
  "Monteria",
  "Neiva",
  "Valledupar",
  "Armenia",
  "Popayan",
  "Sincelejo",
  "Tunja",
  "Florencia",
  "Riohacha",
  "Quibdo",
  "Yopal",
  "Sogamoso",
  "Duitama",
  "Barrancabermeja",
  "Palmira",
  "Buenaventura",
  "Tulua",
  "Buga",
  "Cartago",
  "Soledad",
  "Envigado",
  "Itagui",
  "Bello",
  "Apartado",
  "Rionegro",
  "Turbo",
  "Caucasia",
  "Sabaneta",
  "La Estrella",
  "Caldas",
  "Copacabana",
  "Girardota",
  "Barbosa",
  "Marinilla",
  "El Carmen de Viboral",
  "La Ceja",
  "San Gil",
  "Girardot",
  "Fusagasuga",
  "Zipaquira",
  "Facatativa",
  "Chia",
  "Mosquera",
  "Madrid",
  "Funza",
  "Soacha",
  "Cajica",
  "La Calera",
  "Tabio",
  "Tenjo",
  "Cota",
  "Sibate",
  "Tocancipa",
  "Gachancipa",
  "Sopó",
  "Ubaté",
  "Chiquinquira",
  "Puerto Boyaca",
  "Paipa",
  "Turmequé",
  "Villa de Leyva",
  "Aguachica",
  "Ocana",
  "Pamplona",
  "Los Patios",
  "Villa del Rosario",
  "Ipiales",
  "Tumaco",
  "La Union",
  "Samaniego",
  "Pitalito",
  "Garzon",
  "La Plata",
  "Campoalegre",
  "Espinal",
  "Melgar",
  "Honda",
  "Mariquita",
  "Lerida",
  "Chaparral",
  "Dosquebradas",
  "La Virginia",
  "Santa Rosa de Cabal",
  "Chinchina",
  "Villamaria",
  "Anserma",
  "Riosucio",
  "Magangue",
  "El Carmen de Bolivar",
  "Turbaco",
  "Arjona",
  "San Juan Nepomuceno",
  "Lorica",
  "Cerete",
  "Sahagun",
  "Planeta Rica",
  "Tierralta",
  "Montelibano",
  "Ciénaga",
  "Fundacion",
  "El Banco",
  "Plato",
  "Aracataca",
  "Pivijay",
  "Maicao",
  "Uribia",
  "Fonseca",
  "San Juan del Cesar",
  "Leticia",
  "Puerto Asis",
  "Mocoa",
  "San Jose del Guaviare",
  "Inirida",
  "Mitu",
  "Puerto Carreno",
  "Arauca",
  "Tame",
  "Saravena",
  "Aguazul",
  "Paz de Ariporo",
  "Villanueva",
  "Monterrey",
  "Acacias",
  "Granada",
  "Puerto Lopez",
  "San Martin",
  "Istmina",
  "Tado",
  "Condoto",
  "San Andres",
  "Providencia",
  "Corozal",
  "Ovejas",
  "San Marcos",
  "Tolu",
  "San Onofre",
  "Calamar",
  "San Vicente del Caguan",
  "El Doncello",
  "Puerto Rico",
  "Belen de los Andaquies",
  "Albania",
  "La Dorada",
  "Pensilvania",
  "Manzanares",
  "Salamina",
  "Neira",
  "Pacora",
  "Supía",
  "Viterbo",
  "Sevilla",
  "Caicedonia",
  "Zarzal",
  "Roldanillo",
  "Dagua",
  "Jamundi",
  "Yumbo",
  "Candelaria",
  "Florida",
  "Pradera",
  "El Cerrito",
  "Guacari",
  "Andalucia",
  "Obando",
  "Toro",
  "La Victoria",
  "Bolivar",
  "Santander de Quilichao",
  "Puerto Tejada",
  "Piendamo",
  "El Bordo",
  "Guapi",
  "Miranda",
  "Corinto",
  "Caloto",
  "Silvia",
  "Toribio",
  "Chía",
  "Nemocon",
  "Suesca",
  "Villapinzon",
  "Guaduas",
  "Villeta",
  "La Mesa",
  "Anapoima",
  "Ricaurte",
  "Flandes",
  "Tocaima",
  "Agua de Dios",
  "Nilo",
  "Carmen de Apicala",
  "Silvania",
  "San Bernardo",
  "Arbelaez",
  "Pasca",
  "Ubaque",
  "Choachi",
  "Fomeque",
  "Junín",
  "Guasca",
  "Sesquile",
  "Guatavita",
  "Macheta",
  "Chocontá",
  "Sutatenza",
  "Guateque",
  "Garagoa",
  "Miraflores",
  "Moniquirá",
  "Barbosa Santander",
  "Oiba",
  "Socorro",
  "Charalá",
  "Velez",
  "Puente Nacional",
  "Zapatoca",
  "San Vicente de Chucurí",
  "Lebrija",
  "Giron",
  "Piedecuesta",
  "Floridablanca",
  "Rionegro Santander",
  "Matanza",
  "California",
  "Malaga",
  "Capitanejo",
  "Chinacota",
  "Bochalema",
  "Salazar",
  "Sardinata",
  "Tibu",
  "Convencion",
  "El Zulia",
  "San Cayetano",
  "Durania",
  "Puerto Santander",
  "Herrán",
  "Toledo",
  "Labateca",
  "Chitaga",
]
